theme: jekyll-theme-cayman
# Setup
title:        Chatbot PHP Facebook
description: Chatbot Para Facebook Feito Em PHP Orientado a Objetos
show_downloads: true
tagline:      Chatbot Para Facebook Feito Em PHP Orientado a Objetos
baseurl:      "/ChatBot-PHP-Facebook"
paginate:     1

# About/contact
author:
  name:       Paulão Developer
  url:        https://paulaodev.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
